# Generated by Django 4.2.1 on 2023-06-22 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_user', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=220)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ideas.user')),
            ],
        ),
        migrations.CreateModel(
            name='Project_ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('project_title', models.CharField(max_length=220)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.course')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ideas.user')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.technology')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ideas.user'),
        ),
    ]
