# Generated by Django 4.2.1 on 2023-06-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_course_created_user_project_ideas_created_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_ideas',
            name='technology',
        ),
        migrations.AddField(
            model_name='project_ideas',
            name='technology',
            field=models.ManyToManyField(blank=True, to='ideas.technology'),
        ),
    ]
