# Generated by Django 4.2.1 on 2023-06-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_remove_project_ideas_technology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_ideas',
            name='project_type',
            field=models.IntegerField(choices=[(0, 'mini project'), (1, 'main project'), (2, 'live project')]),
        ),
    ]
